networks:
  monitoring:
    driver: bridge

volumes:
  loki-data:

services:
  app-python:
    image: darrpyy/devops:latest
    restart: unless-stopped
    volumes:
      - ./visits.txt:/code/visits.txt
    ports:
      - "5000:5000"
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_PATHS_PROVISIONING: "/etc/grafana/provisioning"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_FEATURE_TOGGLES_ENABLE: "alertingQueryAndExpressionsStepMode,alertingSimplifiedRouting"
    volumes:
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    restart: unless-stopped
    depends_on:
      - loki
    ports:
      - "3000:3000"
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/cfg.yml
    volumes:
      - /var/log:/var/log
      - ./promtail.yaml:/etc/promtail/cfg.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    restart: unless-stopped
    depends_on:
      - loki
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitoring
